# SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

import copy
import json
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "Tools"))

import vao04
import vao04_interop
from vao04_runtime import Interpreter, verify_trace

FIXTURE = (
    ROOT / "Fixtures/VAO04/descriptors/kinoorgel-multimodal-scientific.example.json"
)
ACOUSTIC_FIXTURE = (
    ROOT / "Fixtures/VAO04/descriptors/cuntz-positiv-acoustic.example.json"
)


def fixture() -> dict:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


class SemanticTests(unittest.TestCase):
    def test_negative_semantic_contracts(self) -> None:
        cases = [
            (
                "immutable schema",
                lambda m: m.__setitem__(
                    "$schema", "https://w3id.org/modavis/vao/0.4/schema/manifest.json"
                ),
            ),
            (
                "immutable context",
                lambda m: m.__setitem__(
                    "@context", ["https://w3id.org/modavis/vao/0.4/context.jsonld"]
                ),
            ),
            (
                "canonical context ordering",
                lambda m: m["@context"].insert(
                    0, "https://example.org/unpinned-context.jsonld"
                ),
            ),
            ("exact format", lambda m: m.__setitem__("formatVersion", "0.4")),
            (
                "JSON Schema format is asserted",
                lambda m: m.__setitem__("extensions", {"not a URI": {}}),
            ),
            ("closed root", lambda m: m.__setitem__("script", "unsafe()")),
            (
                "typed analysis",
                lambda m: m["scientific"]["analyses"].append(
                    {"id": "urn:minimal", "script": "opaque()"}
                ),
            ),
            (
                "analysis activity",
                lambda m: m["scientific"]["analyses"][0].__setitem__(
                    "activityId", "urn:missing"
                ),
            ),
            (
                "activity immutable input output overlap",
                lambda m: m["scientific"]["activities"][2]["inputIds"].append(
                    m["scientific"]["activities"][2]["outputIds"][0]
                ),
            ),
            (
                "observation must be generated by its activity",
                lambda m: m["scientific"]["activities"][2]["outputIds"].remove(
                    m["scientific"]["observations"][0]["id"]
                ),
            ),
            (
                "processed observation result must be an activity output",
                lambda m: m["scientific"]["observations"][0].__setitem__(
                    "processedResultRealizationId",
                    m["scientific"]["activities"][2]["inputIds"][0],
                ),
            ),
            (
                "analysis activity kind and declared I/O",
                lambda m: m["scientific"]["analyses"][0].__setitem__(
                    "activityId", "urn:vao:fixture:kinoorgel:activity:capture"
                ),
            ),
            (
                "deterministic analysis requires execution-specific software evidence",
                lambda m: m["scientific"]["analyses"][0].__setitem__(
                    "reproducibility", "deterministic"
                ),
            ),
            (
                "analysis activity software environment is mandatory",
                lambda m: m["scientific"]["activities"][2].pop("softwareEnvironmentId"),
            ),
            (
                "analysis parameters match activity provenance",
                lambda m: m["scientific"]["analyses"][0]["parameters"].__setitem__(
                    "https://w3id.org/modavis/vao/ontology#thresholdDB", -47
                ),
            ),
            (
                "analysis validation cannot self-reference",
                lambda m: m["scientific"]["analyses"][0].__setitem__(
                    "validationIds", [m["scientific"]["analyses"][0]["id"]]
                ),
            ),
            (
                "analysis output names a different generating activity",
                lambda m: m["scientific"]["observations"][0].__setitem__(
                    "activityId", "urn:vao:fixture:kinoorgel:activity:capture"
                ),
            ),
            (
                "seeded analysis source",
                lambda m: (
                    m["scientific"]["analyses"][0].__setitem__(
                        "reproducibility", "seeded"
                    ),
                    m["scientific"]["analyses"][0].__setitem__(
                        "randomSourceId", "urn:missing"
                    ),
                ),
            ),
            (
                "activity random source record type",
                lambda m: m["scientific"]["activities"][0].__setitem__(
                    "randomSourceId", m["id"]
                ),
            ),
            (
                "analysis and activity random source mismatch",
                lambda m: (
                    m["runtime"]["randomSources"].append(
                        {
                            "id": "urn:vao:test:random:analysis",
                            "algorithm": "pcg32",
                            "seed": "0000000000000001",
                            "stream": "0000000000000000",
                        }
                    ),
                    m["scientific"]["analyses"][0].__setitem__(
                        "reproducibility", "seeded"
                    ),
                    m["scientific"]["analyses"][0].__setitem__(
                        "randomSourceId", "urn:vao:test:random:analysis"
                    ),
                ),
            ),
            (
                "claim one value",
                lambda m: m["scientific"]["claims"].append(
                    {
                        "id": "urn:claim",
                        "subjectId": m["id"],
                        "predicate": "https://example.org/p",
                        "objectId": m["id"],
                        "literal": {"value": "also"},
                        "status": "asserted",
                        "evidenceIds": [m["scientific"]["observations"][0]["id"]],
                    }
                ),
            ),
            (
                "accepted claim without accepting review",
                lambda m: m["scientific"]["claims"].append(
                    {
                        "id": "urn:vao:test:claim:accepted-without-review",
                        "subjectId": m["id"],
                        "predicate": "https://example.org/predicate",
                        "literal": {"value": "unsupported acceptance"},
                        "status": "accepted",
                        "evidenceIds": [m["scientific"]["observations"][0]["id"]],
                    }
                ),
            ),
            (
                "inferred claim without inference activity",
                lambda m: m["scientific"]["claims"].append(
                    {
                        "id": "urn:vao:test:claim:unsupported-inference",
                        "subjectId": m["id"],
                        "predicate": "https://example.org/predicate",
                        "literal": {"value": "unsupported inference"},
                        "status": "inferred",
                        "evidenceIds": [m["scientific"]["observations"][0]["id"]],
                        "generatedById": "urn:vao:fixture:kinoorgel:activity:capture",
                    }
                ),
            ),
            (
                "consent agent",
                lambda m: m["scientific"]["consents"][0].__setitem__(
                    "grantedByAgentId", "urn:missing"
                ),
            ),
            (
                "track timebase",
                lambda m: m["multimodal"]["tracks"][0].__setitem__(
                    "timebaseId", "urn:missing"
                ),
            ),
            (
                "track modality-realization mismatch",
                lambda m: m["multimodal"]["tracks"][0].__setitem__(
                    "realizationId",
                    "urn:vao:fixture:kinoorgel:realization:midi",
                ),
            ),
            (
                "track timebase-realization mismatch",
                lambda m: m["multimodal"]["tracks"][1].__setitem__(
                    "timebaseId", "urn:vao:fixture:kinoorgel:timebase:audio"
                ),
            ),
            (
                "track sample rate-timebase mismatch",
                lambda m: m["realizations"][0]["technicalMetadata"].__setitem__(
                    "sampleRate", 96000
                ),
            ),
            (
                "audio channel label cardinality",
                lambda m: m["realizations"][0]["technicalMetadata"].__setitem__(
                    "channelLabels", ["left"]
                ),
            ),
            (
                "wall-clock timebase without epoch",
                lambda m: m["multimodal"]["timebases"][0].__setitem__(
                    "kind", "wall-clock"
                ),
            ),
            (
                "timebase coordinate-rate unit mismatch",
                lambda m: m["multimodal"]["timebases"][0].__setitem__(
                    "rateUnit", "http://qudt.org/vocab/unit/FRAME-PER-SEC"
                ),
            ),
            (
                "clock overlap",
                lambda m: m["multimodal"]["synchronizationMappings"][0][
                    "segments"
                ].append(
                    copy.deepcopy(
                        m["multimodal"]["synchronizationMappings"][0]["segments"][0]
                    )
                ),
            ),
            (
                "clock segment without explicit boundary status",
                lambda m: m["multimodal"]["synchronizationMappings"][0]["segments"][
                    0
                ].pop("discontinuityAfter"),
            ),
            (
                "undeclared discontinuous clock boundary",
                lambda m: m["multimodal"]["synchronizationMappings"][0][
                    "segments"
                ].append(
                    {
                        **copy.deepcopy(
                            m["multimodal"]["synchronizationMappings"][0]["segments"][0]
                        ),
                        "sourceStart": 960,
                        "sourceEndExclusive": 1920,
                        "offset": 1,
                    }
                ),
            ),
            (
                "clock residual uses wrong coordinate unit",
                lambda m: m["multimodal"]["synchronizationMappings"][0]["segments"][0][
                    "residualUncertainty"
                ].__setitem__("unit", "http://qudt.org/vocab/unit/MilliSEC"),
            ),
            (
                "clock self map",
                lambda m: m["multimodal"]["synchronizationMappings"][0].__setitem__(
                    "targetTimebaseId",
                    m["multimodal"]["synchronizationMappings"][0]["sourceTimebaseId"],
                ),
            ),
            (
                "synchronization method activity lineage",
                lambda m: m["multimodal"]["synchronizationMappings"][0].__setitem__(
                    "activityId", "urn:vao:fixture:kinoorgel:activity:capture"
                ),
            ),
            (
                "annotation track",
                lambda m: m["multimodal"]["annotations"][0]["target"].__setitem__(
                    "trackId", "urn:missing"
                ),
            ),
            (
                "annotation half-open selector pair",
                lambda m: m["multimodal"]["annotations"][0]["target"].pop(
                    "endExclusive"
                ),
            ),
            (
                "annotation creator absent from activity",
                lambda m: m["multimodal"]["annotations"][0].__setitem__(
                    "createdByAgentId", "urn:vao:agent:vao04-migrator"
                ),
            ),
            (
                "annotation missing creation time",
                lambda m: m["multimodal"]["annotations"][0].pop("createdAt"),
            ),
            (
                "annotation missing provenance activity",
                lambda m: m["multimodal"]["annotations"][0].pop("activityId"),
            ),
            (
                "physical port",
                lambda m: m["physicalSystem"]["ports"][0].__setitem__(
                    "componentId", "urn:missing"
                ),
            ),
            (
                "physical connection",
                lambda m: m["physicalSystem"]["connections"][0].__setitem__(
                    "targetPortId", "urn:missing"
                ),
            ),
            (
                "bidirectional connection on directional ports",
                lambda m: m["physicalSystem"]["connections"][0].__setitem__(
                    "bidirectional", True
                ),
            ),
            (
                "sensor protocol",
                lambda m: m["physicalSystem"]["sensors"][0].__setitem__(
                    "protocolId", "urn:missing"
                ),
            ),
            (
                "MIDI 2 group",
                lambda m: next(
                    x
                    for x in m["interactionModel"]["protocolBindings"]
                    if x["protocol"] == "MIDI-2.0"
                ).pop("umpGroup"),
            ),
            (
                "MIDI 2 JR",
                lambda m: next(
                    x
                    for x in m["interactionModel"]["protocolBindings"]
                    if x["protocol"] == "MIDI-2.0"
                ).__setitem__("jrTimestamp", False),
            ),
            (
                "stochastic distribution",
                lambda m: (
                    m["interactionModel"]["processModels"][0].__setitem__(
                        "processKind", "stochastic"
                    ),
                    m["interactionModel"]["processModels"][0].__setitem__(
                        "ordering", "stochastic"
                    ),
                ),
            ),
            (
                "non-stochastic process ordering",
                lambda m: m["interactionModel"]["processModels"][0].__setitem__(
                    "ordering", "stochastic"
                ),
            ),
            (
                "missing cancellation control for termination policy",
                lambda m: m["interactionModel"]["processModels"][0].pop(
                    "cancellationControlId"
                ),
            ),
            (
                "irrelevant process iteration bound",
                lambda m: m["interactionModel"]["processModels"][1].__setitem__(
                    "maximumIterations", 4
                ),
            ),
            (
                "missing process duration bound",
                lambda m: m["interactionModel"]["processModels"][1].__setitem__(
                    "terminationPolicy", "duration-bound"
                ),
            ),
            (
                "transfer domain",
                lambda m: m["interactionModel"]["transferFunctions"][0].update(
                    {"validDomain": [[1, 1]], "extrapolationPolicy": "reject"}
                ),
            ),
            (
                "content digest",
                lambda m: m["realizations"][0].__setitem__(
                    "contentDigests", [{"algorithm": "sha256", "value": "0" * 64}]
                ),
            ),
            (
                "asset group materializes a non-profile record",
                lambda m: m["assetGroups"][0]["materializesProfileIds"].append(m["id"]),
            ),
            (
                "chunk indices",
                lambda m: m["realizations"][0].__setitem__(
                    "chunking",
                    {
                        "strategy": "fixed-size",
                        "chunks": [
                            {
                                "index": 1,
                                "offset": 0,
                                "length": m["realizations"][0]["byteSize"],
                                "digest": {
                                    "algorithm": "sha256",
                                    "value": m["realizations"][0]["sha256"],
                                },
                            }
                        ],
                    },
                ),
            ),
            (
                "Merkle root",
                lambda m: m["realizations"][0].__setitem__(
                    "chunking",
                    {
                        "strategy": "fixed-size",
                        "merkleRoot": {"algorithm": "sha256", "value": "0" * 64},
                        "chunks": [
                            {
                                "index": 0,
                                "offset": 0,
                                "length": m["realizations"][0]["byteSize"],
                                "digest": {
                                    "algorithm": "sha256",
                                    "value": m["realizations"][0]["sha256"],
                                },
                            }
                        ],
                    },
                ),
            ),
            (
                "rights consent",
                lambda m: m["rights"][0].__setitem__("consentIds", ["urn:missing"]),
            ),
            (
                "community authority",
                lambda m: m["rights"][0].__setitem__(
                    "privacyClassification", "community-governed"
                ),
            ),
            (
                "discovery creator",
                lambda m: m["discovery"].__setitem__(
                    "creatorAgentIds", ["urn:missing"]
                ),
            ),
            (
                "scientific profile",
                lambda m: (
                    m.__setitem__(
                        "profiles",
                        [
                            x
                            for x in m["profiles"]
                            if x["id"] != vao04.SCIENTIFIC_PROFILE
                        ],
                    ),
                    m.__setitem__(
                        "conformsTo",
                        [x for x in m["conformsTo"] if x != vao04.SCIENTIFIC_PROFILE],
                    ),
                ),
            ),
            (
                "multimodal profile",
                lambda m: (
                    m.__setitem__(
                        "profiles",
                        [
                            x
                            for x in m["profiles"]
                            if x["id"] != vao04.MULTIMODAL_PROFILE
                        ],
                    ),
                    m.__setitem__(
                        "conformsTo",
                        [x for x in m["conformsTo"] if x != vao04.MULTIMODAL_PROFILE],
                    ),
                ),
            ),
            (
                "runtime profile",
                lambda m: (
                    m.__setitem__(
                        "profiles",
                        [x for x in m["profiles"] if x["id"] != vao04.RUNTIME_PROFILE],
                    ),
                    m.__setitem__(
                        "conformsTo",
                        [x for x in m["conformsTo"] if x != vao04.RUNTIME_PROFILE],
                    ),
                ),
            ),
        ]
        for name, mutate in cases:
            with self.subTest(name=name):
                value = fixture()
                mutate(value)
                report = vao04.validate_manifest(value)
                self.assertFalse(report["valid"], name)
                self.assertTrue(report["errors"], name)

    def test_deterministic_renderer_requires_execution_specific_identity(self) -> None:
        value = json.loads(ACOUSTIC_FIXTURE.read_text(encoding="utf-8"))
        value["runtime"]["renderers"][0]["deterministic"] = True
        report = vao04.validate_manifest(value)
        self.assertFalse(report["valid"])
        self.assertTrue(
            any("Renderer" in error and "exact" in error for error in report["errors"]),
            report["errors"],
        )

    def test_reproducibility_requires_code_and_environment_evidence(self) -> None:
        value = fixture()
        analysis = value["scientific"]["analyses"][0]
        environment = next(
            item
            for item in value["scientific"]["softwareEnvironments"]
            if item["id"] == analysis["softwareEnvironmentId"]
        )
        analysis["reproducibility"] = "deterministic"
        environment["identityScope"] = "source-file"
        environment["identityDescription"] = "SHA-256 of the exact analysis source."
        environment["runtimeDescription"] = "CPython 3.14 on a declared target host."
        report = vao04.validate_manifest(value)
        self.assertFalse(report["valid"])
        self.assertTrue(
            any("Analysis" in error and "exact" in error for error in report["errors"])
        )

        environment["dependencies"] = [
            {
                "name": "analysis-environment.lock",
                "dependencyRole": "environment-lock",
                "identity": {"algorithm": "sha256", "value": "1" * 64},
                "identityScope": "environment-lock",
                "identityDescription": "SHA-256 of the exact dependency lock.",
            }
        ]
        self.assertTrue(vao04.validate_manifest(value)["valid"])

        environment["identityScope"] = "environment-lock"
        environment["identityDescription"] = "SHA-256 of only the environment lock."
        environment.pop("dependencies")
        self.assertFalse(vao04.validate_manifest(value)["valid"])

    def test_stochastic_candidates_are_direct_actions_then_children(self) -> None:
        value = fixture()
        source_id = "urn:vao:test:random:process-candidates"
        value["runtime"]["randomSources"].append(
            {
                "id": source_id,
                "algorithm": "pcg32",
                "seed": "0000000000000001",
                "stream": "0000000000000001",
            }
        )
        child_id = "urn:vao:test:process:candidate-child"
        value["interactionModel"]["processModels"].extend(
            [
                {
                    "id": child_id,
                    "processKind": "one-shot",
                    "ordering": "single",
                    "actions": [
                        {
                            "operation": "emit-event",
                            "targetId": "urn:vao:fixture:kinoorgel:event:telephone-pulse",
                        },
                        {
                            "operation": "emit-event",
                            "targetId": "urn:vao:fixture:kinoorgel:event:telephone-pulse",
                        },
                    ],
                    "terminationPolicy": "completed",
                    "status": "asserted",
                    "source": "documented",
                },
                {
                    "id": "urn:vao:test:process:candidate-parent",
                    "processKind": "stochastic",
                    "ordering": "stochastic",
                    "actions": [
                        {
                            "operation": "emit-event",
                            "targetId": "urn:vao:fixture:kinoorgel:event:telephone-pulse",
                        }
                    ],
                    "childProcessIds": [child_id],
                    "terminationPolicy": "completed",
                    "status": "asserted",
                    "source": "documented",
                    "randomSourceId": source_id,
                    "probabilityDistribution": {
                        "kind": "categorical",
                        "parameters": {"1": 1},
                    },
                },
            ]
        )
        self.assertTrue(vao04.validate_manifest(value)["valid"])

        parent = value["interactionModel"]["processModels"][-1]
        parent["probabilityDistribution"]["parameters"] = {"2": 1}
        self.assertFalse(vao04.validate_manifest(value)["valid"])

        parent["probabilityDistribution"]["parameters"] = {"1" * 5_000: 1}
        self.assertFalse(vao04.validate_manifest(value)["valid"])

    def test_golden_trace_and_tamper_detection(self) -> None:
        value = fixture()
        trace = value["runtime"]["conformanceTraces"][0]
        self.assertEqual(
            trace["expected"],
            Interpreter(value).execute(trace["inputEvents"], trace.get("initialState")),
        )
        self.assertEqual([], verify_trace(value, trace))
        corrupted = copy.deepcopy(trace)
        key = "urn:vao:fixture:kinoorgel:state:tibia-enabled"
        corrupted["expected"]["state"][key] = not corrupted["expected"]["state"][key]
        self.assertTrue(verify_trace(value, corrupted))

        sha512_trace = fixture()
        sha512_trace["runtime"]["conformanceTraces"][0]["digest"] = {
            "algorithm": "sha512",
            "value": "0" * 128,
        }
        self.assertTrue(vao04.schema_errors(sha512_trace, vao04.MANIFEST_SCHEMA))

    def test_rc2_blocking_regressions(self) -> None:
        cases = [
            (
                "global identifier collision",
                lambda m: m["physicalSystem"]["components"][0].__setitem__(
                    "id", m["scientific"]["agents"][0]["id"]
                ),
            ),
            (
                "physical parent cycle",
                lambda m: (
                    m["physicalSystem"]["components"][0].__setitem__(
                        "parentComponentId",
                        m["physicalSystem"]["components"][1]["id"],
                    ),
                    m["physicalSystem"]["components"][1].__setitem__(
                        "parentComponentId",
                        m["physicalSystem"]["components"][0]["id"],
                    ),
                ),
            ),
            (
                "runtime semantics mismatch",
                lambda m: m["runtime"]["executionSemantics"].__setitem__(
                    "maximumMicrosteps", 9999
                ),
            ),
            (
                "non-numeric observation",
                lambda m: m["scientific"]["observations"][0]["result"].__setitem__(
                    "value", "not-a-measurement"
                ),
            ),
            (
                "negative standard uncertainty",
                lambda m: m["scientific"]["observations"][0]["result"].__setitem__(
                    "uncertainty",
                    {
                        "kind": "standard",
                        "value": -1,
                        "unit": m["scientific"]["observations"][0]["result"]["unit"],
                    },
                ),
            ),
            (
                "invalid ORCID checksum",
                lambda m: m["scientific"]["agents"][0].__setitem__(
                    "orcid", "https://orcid.org/0000-0002-7904-3893"
                ),
            ),
            (
                "uncontrolled DataCite relation",
                lambda m: m["discovery"]["relatedIdentifiers"].append(
                    {
                        "identifier": "https://doi.org/10.0000/example",
                        "identifierType": "DOI",
                        "relationType": "ApproximatelyRelatedTo",
                    }
                ),
            ),
            (
                "invalid DataCite DOI lexical form",
                lambda m: m["discovery"]["relatedIdentifiers"].append(
                    {
                        "identifier": "not-a-doi",
                        "identifierType": "DOI",
                        "relationType": "References",
                    }
                ),
            ),
            (
                "missing realization provenance",
                lambda m: m["realizations"][0].__setitem__("provenanceIds", []),
            ),
            (
                "provenance activity omits realization output",
                lambda m: m["scientific"]["activities"][1]["outputIds"].remove(
                    m["realizations"][0]["id"]
                ),
            ),
            (
                "generated record omitted from activity outputs",
                lambda m: m["interactionModel"]["transitions"][0].__setitem__(
                    "generatedById",
                    "urn:vao:fixture:kinoorgel:activity:latency-analysis",
                ),
            ),
            (
                "origin status conflicts with generating activity",
                lambda m: m["realizations"][0].__setitem__(
                    "representationStatus",
                    "https://w3id.org/modavis/vao/vocab/representation-status/simulated",
                ),
            ),
            (
                "duplicate content-digest algorithm",
                lambda m: m["realizations"][0].__setitem__(
                    "contentDigests",
                    [
                        {"algorithm": "sha256", "value": "f" * 64},
                        {
                            "algorithm": "sha256",
                            "value": m["realizations"][0]["sha256"],
                        },
                    ],
                ),
            ),
            (
                "state action targets wrong record class",
                lambda m: m["interactionModel"]["transitions"][0]["actions"][
                    0
                ].__setitem__("targetId", m["primaryEntityId"]),
            ),
        ]
        for name, mutate in cases:
            with self.subTest(name=name):
                value = fixture()
                mutate(value)
                self.assertFalse(vao04.validate_manifest(value)["valid"], name)

    def test_rfc3339_order_is_chronological_not_lexical(self) -> None:
        valid = fixture()
        activity = valid["scientific"]["activities"][0]
        activity["startedAt"] = "2026-01-01T01:00:00+02:00"
        activity["endedAt"] = "2026-01-01T00:30:00+00:00"
        self.assertTrue(vao04.validate_manifest(valid)["valid"])

        invalid = fixture()
        activity = invalid["scientific"]["activities"][0]
        activity["startedAt"] = "2026-01-01T00:30:00+00:00"
        activity["endedAt"] = "2026-01-01T01:00:00+02:00"
        self.assertFalse(vao04.validate_manifest(invalid)["valid"])

        submicrosecond = fixture()
        activity = submicrosecond["scientific"]["activities"][0]
        activity["startedAt"] = "2026-01-01T00:00:00.0000002Z"
        activity["endedAt"] = "2026-01-01T00:00:00.0000001Z"
        self.assertFalse(vao04.validate_manifest(submicrosecond)["valid"])

        lowercase = fixture()
        activity = lowercase["scientific"]["activities"][0]
        activity["startedAt"] = "2026-01-01t00:00:00.0000001z"
        activity["endedAt"] = "2026-01-01t00:00:00.0000002z"
        self.assertTrue(vao04.validate_manifest(lowercase)["valid"])

        leap_second = fixture()
        leap_second["modifiedAt"] = "2016-12-31T23:59:60Z"
        self.assertFalse(vao04.validate_manifest(leap_second)["valid"])

        excess_precision = fixture()
        excess_precision["modifiedAt"] = "2026-01-01T00:00:00.1234567890123456789Z"
        self.assertFalse(vao04.validate_manifest(excess_precision)["valid"])

    def test_absolute_timebases_declare_their_time_scale(self) -> None:
        value = fixture()
        value["multimodal"]["timebases"].append(
            {
                "id": "urn:vao:test:timebase:absolute",
                "kind": "wall-clock",
                "unit": "http://qudt.org/vocab/unit/SEC",
                "rate": 1,
                "rateUnit": "http://qudt.org/vocab/unit/UNITLESS",
                "origin": 0,
                "epoch": "2026-01-01T00:00:00Z",
                "timeScale": "https://w3id.org/modavis/vao/vocab/time-scale/utc",
            }
        )
        self.assertTrue(vao04.validate_manifest(value)["valid"])

        value["multimodal"]["timebases"][-1].pop("timeScale")
        self.assertFalse(vao04.validate_manifest(value)["valid"])

    def test_interoperable_json_numeric_domain(self) -> None:
        value = fixture()
        value["release"]["revision"] = vao04.MAX_SAFE_INTEGER
        self.assertTrue(vao04.validate_manifest(value)["valid"])

        value["release"]["revision"] = vao04.MAX_SAFE_INTEGER + 1
        self.assertFalse(vao04.validate_manifest(value)["valid"])

        with self.assertRaises(vao04.vao03.VAO03Error):
            vao04.strict_json_bytes(b'{"value":1e-400}', "underflow test")
        with self.assertRaises(vao04.vao03.VAO03Error):
            vao04.strict_json_bytes(b'{"value":"\\ud800"}', "non-scalar Unicode test")

        value = fixture()
        value["title"]["en"] = "\ud800"
        self.assertFalse(vao04.validate_manifest(value)["valid"])

        value = fixture()
        value["runtime"]["randomSources"].append(
            {
                "id": "urn:vao:test:random:large-stream",
                "algorithm": "pcg32",
                "seed": "0000000000000001",
                "stream": "7fffffffffffffff",
            }
        )
        self.assertTrue(vao04.validate_manifest(value)["valid"])

        value["runtime"]["randomSources"][-1]["stream"] = 9007199254740992
        self.assertFalse(vao04.validate_manifest(value)["valid"])

        value = fixture()
        nested: dict[str, object] = {}
        cursor = nested
        for index in range(vao04.MAX_JSON_DEPTH + 1):
            child: dict[str, object] = {}
            cursor[f"level{index}"] = child
            cursor = child
        value["extensions"] = {"https://example.org/deep-extension": nested}
        report = vao04.validate_manifest(value)
        self.assertFalse(report["valid"])
        self.assertIn("JSON nesting limit", "\n".join(report["errors"]))

    def test_ror_checksum(self) -> None:
        value = fixture()
        organization = {
            "id": "urn:vao:test:organization:jena",
            "agentKind": "organization",
            "labels": {"en": "Friedrich Schiller University Jena"},
            "ror": "https://ror.org/05qpz1x62",
        }
        value["scientific"]["agents"].append(organization)
        person = next(
            agent
            for agent in value["scientific"]["agents"]
            if agent["agentKind"] == "person"
        )
        person["affiliationAgentIds"] = [organization["id"]]
        self.assertTrue(vao04.validate_manifest(value)["valid"])
        datacite_creator = vao04_interop.datacite(value)["data"]["attributes"][
            "creators"
        ][0]
        self.assertEqual(
            "https://ror.org/05qpz1x62",
            datacite_creator["affiliation"][0]["affiliationIdentifier"],
        )
        organization["ror"] = "https://ror.org/05qpz1x63"
        self.assertFalse(vao04.validate_manifest(value)["valid"])

    def test_claim_review_decision_chain(self) -> None:
        value = fixture()
        claim_id = "urn:vao:test:claim:reviewed"
        review_id = "urn:vao:test:review:accepted"
        value["scientific"]["claims"].append(
            {
                "id": claim_id,
                "subjectId": value["id"],
                "predicate": "https://example.org/predicate",
                "literal": {"value": "reviewed conclusion"},
                "status": "accepted",
                "evidenceIds": [value["scientific"]["observations"][0]["id"]],
                "reviewIds": [review_id],
            }
        )
        value["scientific"]["reviews"].append(
            {
                "id": review_id,
                "reviewedId": claim_id,
                "reviewerAgentId": "urn:vao:fixture:kinoorgel:agent:performer",
                "reviewedAt": "2026-08-25T10:03:00Z",
                "decision": "accepted",
            }
        )
        self.assertTrue(vao04.validate_manifest(value)["valid"])

        value["scientific"]["reviews"][0]["decision"] = "not-assessed"
        self.assertFalse(vao04.validate_manifest(value)["valid"])

    def test_scientific_temporal_and_evidence_integrity(self) -> None:
        value = fixture()
        claim_a = "urn:vao:test:claim:cycle-a"
        claim_b = "urn:vao:test:claim:cycle-b"
        for identifier, evidence in ((claim_a, claim_b), (claim_b, claim_a)):
            value["scientific"]["claims"].append(
                {
                    "id": identifier,
                    "subjectId": value["id"],
                    "predicate": "https://example.org/predicate",
                    "literal": {"value": "circular evidence"},
                    "status": "asserted",
                    "evidenceIds": [evidence],
                }
            )
        self.assertFalse(vao04.validate_manifest(value)["valid"])

        value = fixture()
        claim_id = "urn:vao:test:claim:premature-review"
        review_id = "urn:vao:test:review:premature"
        activity = value["scientific"]["activities"][2]
        activity["outputIds"].append(claim_id)
        value["scientific"]["claims"].append(
            {
                "id": claim_id,
                "subjectId": value["id"],
                "predicate": "https://example.org/predicate",
                "literal": {"value": "conclusion"},
                "status": "accepted",
                "evidenceIds": [value["scientific"]["observations"][0]["id"]],
                "generatedById": activity["id"],
                "reviewIds": [review_id],
            }
        )
        value["scientific"]["reviews"].append(
            {
                "id": review_id,
                "reviewedId": claim_id,
                "reviewerAgentId": "urn:vao:fixture:kinoorgel:agent:performer",
                "reviewedAt": "2026-08-25T10:01:59Z",
                "decision": "accepted",
            }
        )
        self.assertFalse(vao04.validate_manifest(value)["valid"])

        value = fixture()
        observation_id = value["scientific"]["observations"][0]["id"]
        resampling = value["scientific"]["activities"][4]
        resampling["inputIds"] = [observation_id]
        report = vao04.validate_manifest(value)
        self.assertFalse(report["valid"])
        self.assertTrue(
            any("starts before input" in error for error in report["errors"])
        )

        value = fixture()
        capture = value["scientific"]["activities"][1]
        capture["inputIds"].append(value["scientific"]["observations"][0]["id"])
        report = vao04.validate_manifest(value)
        self.assertFalse(report["valid"])
        self.assertTrue(
            any("Activity dependency graph" in error for error in report["errors"])
        )

        value = fixture()
        activity = value["scientific"]["activities"][3]
        review_id = "urn:vao:test:review:future-evidence"
        claim_id = "urn:vao:test:claim:uses-future-evidence"
        activity["inputIds"].append(review_id)
        activity["outputIds"].append(claim_id)
        value["scientific"]["reviews"].append(
            {
                "id": review_id,
                "reviewedId": value["scientific"]["observations"][0]["id"],
                "reviewerAgentId": "urn:vao:fixture:kinoorgel:agent:performer",
                "reviewedAt": "2026-08-25T10:03:00Z",
                "decision": "not-assessed",
            }
        )
        value["scientific"]["claims"].append(
            {
                "id": claim_id,
                "subjectId": value["id"],
                "predicate": "https://example.org/predicate",
                "literal": {"value": "premature conclusion"},
                "status": "asserted",
                "evidenceIds": [review_id],
                "generatedById": activity["id"],
            }
        )
        report = vao04.validate_manifest(value)
        self.assertFalse(report["valid"])
        self.assertTrue(
            any("starts before input" in error for error in report["errors"]),
            report["errors"],
        )

    def test_sensor_calibration_must_match_and_be_time_valid(self) -> None:
        value = fixture()
        observation = value["scientific"]["observations"][0]
        sensor = value["physicalSystem"]["sensors"][0]
        calibration_id = "urn:vao:test:calibration:midi-sensor"
        observation["observedProperty"] = sensor["observedProperty"]
        observation["sensorId"] = sensor["id"]
        observation["calibrationId"] = calibration_id
        sensor["calibrationId"] = calibration_id
        value["scientific"]["calibrations"].append(
            {
                "id": calibration_id,
                "instrumentEntityId": "urn:vao:fixture:kinoorgel:manual:great",
                "protocolId": sensor["protocolId"],
                "performedByAgentIds": ["urn:vao:fixture:kinoorgel:agent:performer"],
                "performedAt": "2026-08-24T10:00:00Z",
                "validUntil": "2026-08-26T10:00:00Z",
                "resultStatus": "pass",
            }
        )
        self.assertTrue(vao04.validate_manifest(value)["valid"])

        value["scientific"]["calibrations"][0]["validUntil"] = "2026-08-25T10:00:00Z"
        self.assertFalse(vao04.validate_manifest(value)["valid"])

        value = fixture()
        observation = value["scientific"]["observations"][0]
        observation["sensorId"] = value["physicalSystem"]["sensors"][0]["id"]
        self.assertFalse(vao04.validate_manifest(value)["valid"])

    def test_covariance_and_acoustic_dimensions(self) -> None:
        value = fixture()
        result = value["scientific"]["observations"][0]["result"]
        result["uncertainty"] = {
            "kind": "covariance",
            "value": [[1, 2], [2, 1]],
            "unit": "http://qudt.org/vocab/unit/M2",
        }
        self.assertFalse(vao04.validate_manifest(value)["valid"])

        acoustic = json.loads(ACOUSTIC_FIXTURE.read_text(encoding="utf-8"))
        acoustic["acoustics"]["metricSets"][0]["metrics"][0]["values"].pop()
        self.assertFalse(vao04.validate_manifest(acoustic)["valid"])

        acoustic = json.loads(ACOUSTIC_FIXTURE.read_text(encoding="utf-8"))
        acoustic["acoustics"]["metricSets"][0]["metrics"][0]["uncertainty"]["unit"] = (
            "http://qudt.org/vocab/unit/M"
        )
        self.assertFalse(vao04.validate_manifest(acoustic)["valid"])

        acoustic = json.loads(ACOUSTIC_FIXTURE.read_text(encoding="utf-8"))
        acoustic["acoustics"]["metricSets"][0]["subjectIds"][0] = acoustic["id"]
        self.assertFalse(vao04.validate_manifest(acoustic)["valid"])

    def test_material_uncertainties_are_property_specific(self) -> None:
        value = json.loads(ACOUSTIC_FIXTURE.read_text(encoding="utf-8"))
        material = value["acoustics"]["materialModels"][0]
        material["absorptionUncertainty"] = {
            "kind": "standard",
            "value": [0.01, 0.01, 0.02, 0.02],
            "unit": "http://qudt.org/vocab/unit/UNITLESS",
        }
        self.assertTrue(vao04.validate_manifest(value)["valid"])

        material["absorptionUncertainty"]["unit"] = "http://qudt.org/vocab/unit/DeciB"
        self.assertFalse(vao04.validate_manifest(value)["valid"])

    def test_small_magnitude_covariance_is_checked_relative_to_its_scale(self) -> None:
        value = fixture()
        result = value["scientific"]["observations"][0]["result"]
        result["value"] = [0.0, 0.0]
        result["uncertainty"] = {
            "kind": "covariance",
            "value": [[1e-20, 2e-20], [2e-20, 1e-20]],
            "unit": result["unit"],
        }
        self.assertFalse(vao04.validate_manifest(value)["valid"])

        result["uncertainty"]["value"] = [[1e-20, 0.0], [0.0, 2e-20]]
        self.assertTrue(vao04.validate_manifest(value)["valid"])

        result["uncertainty"]["value"] = [[1e-20, 0.0], [0.0, 1e20]]
        self.assertTrue(vao04.validate_manifest(value)["valid"])

        result["uncertainty"]["value"] = [[-1e-20, 0.0], [0.0, 1e20]]
        self.assertFalse(vao04.validate_manifest(value)["valid"])

        result["uncertainty"]["value"] = [[0.0, 1e-30], [1e-30, 1e20]]
        self.assertFalse(vao04.validate_manifest(value)["valid"])

        result["value"] = [0.0] * (vao04.MAX_INLINE_COVARIANCE_DIMENSION + 1)
        size = len(result["value"])
        result["uncertainty"]["value"] = [
            [1.0 if row == column else 0.0 for column in range(size)]
            for row in range(size)
        ]
        self.assertFalse(vao04.validate_manifest(value)["valid"])

    def test_timebase_rate_supports_canonical_exact_rationals(self) -> None:
        value = fixture()
        value["multimodal"]["timebases"][0]["rate"] = {
            "numerator": 192000,
            "denominator": 1,
        }
        self.assertTrue(vao04.validate_manifest(value)["valid"])

        value["multimodal"]["timebases"][0]["rate"] = {
            "numerator": 384000,
            "denominator": 2,
        }
        self.assertFalse(vao04.validate_manifest(value)["valid"])

        value = fixture()
        value["multimodal"]["timebases"][0]["rate"] = 192000.0000001
        self.assertFalse(vao04.validate_manifest(value)["valid"])

    def test_piecewise_clock_requires_explicit_continuous_boundaries(self) -> None:
        value = fixture()
        segment = copy.deepcopy(
            value["multimodal"]["synchronizationMappings"][0]["segments"][0]
        )
        segment["sourceStart"] = segment["sourceEndExclusive"]
        segment["sourceEndExclusive"] = 1920
        value["multimodal"]["synchronizationMappings"][0]["segments"].append(segment)
        self.assertTrue(vao04.validate_manifest(value)["valid"])

        segment["offset"] = 1e-10
        self.assertFalse(vao04.validate_manifest(value)["valid"])

    def test_technical_clock_and_frame_references_are_typed(self) -> None:
        value = fixture()
        value["realizations"][0]["technicalMetadata"]["timebaseId"] = value["id"]
        self.assertFalse(vao04.validate_manifest(value)["valid"])

        value = fixture()
        value["realizations"][0]["technicalMetadata"]["coordinateFrameId"] = value["id"]
        self.assertFalse(vao04.validate_manifest(value)["valid"])

        value = json.loads(ACOUSTIC_FIXTURE.read_text(encoding="utf-8"))
        geometry = next(
            realization
            for realization in value["realizations"]
            if realization["technicalMetadata"]["kind"] == "geometry"
        )
        geometry["technicalMetadata"]["coordinateUnit"] = (
            "http://qudt.org/vocab/unit/CentiM"
        )
        self.assertFalse(vao04.validate_manifest(value)["valid"])

        value = fixture()
        track = value["multimodal"]["tracks"][0]
        track["modality"] = "trajectory"
        value["realizations"][1]["technicalMetadata"]["trajectoryTrackId"] = track["id"]
        report = vao04.validate_manifest(value)
        self.assertFalse(report["valid"])
        self.assertTrue(
            any("same Realization" in error for error in report["errors"]),
            report["errors"],
        )

    def test_spatial_and_acoustics_profiles_are_mandatory_when_active(self) -> None:
        for profile in (vao04.SPATIAL_PROFILE, vao04.ACOUSTICS_PROFILE):
            with self.subTest(profile=profile):
                value = json.loads(ACOUSTIC_FIXTURE.read_text(encoding="utf-8"))
                value["profiles"] = [
                    record for record in value["profiles"] if record["id"] != profile
                ]
                value["conformsTo"] = [
                    claim for claim in value["conformsTo"] if claim != profile
                ]
                self.assertFalse(vao04.validate_manifest(value)["valid"])

    def test_spatial_reference_and_transform_contracts(self) -> None:
        mutations = [
            lambda m: m["acoustics"]["geometryBindings"][0].__setitem__(
                "logicalAssetId", "urn:vao:test:missing"
            ),
            lambda m: m["acoustics"]["coordinateFrames"][1].__setitem__(
                "transformToParent",
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
            ),
            lambda m: m["acoustics"]["poses"][2].__setitem__(
                "orientationXYZW", [0, 0, 0, 2]
            ),
            lambda m: (
                m["acoustics"]["poses"][2].__setitem__("interpolation", "linear"),
                m["acoustics"]["poses"][2].__setitem__(
                    "trajectoryRealizationId", m["realizations"][0]["id"]
                ),
            ),
            lambda m: m["acoustics"]["poses"][0].__setitem__(
                "trajectoryRealizationId", m["realizations"][0]["id"]
            ),
            lambda m: m["acoustics"]["poses"][2].pop("localFrameId"),
            lambda m: m["acoustics"]["poses"][0].__setitem__(
                "localFrameId", m["acoustics"]["coordinateFrames"][0]["id"]
            ),
            lambda m: next(
                frame
                for frame in m["acoustics"]["coordinateFrames"]
                if frame["id"] == m["acoustics"]["poses"][2]["localFrameId"]
            ).__setitem__("handedness", "left"),
            lambda m: m["acoustics"]["poses"][2].__setitem__("extent", [1, -1, 1]),
            lambda m: m["acoustics"]["audioScenes"][0].__setitem__(
                "coordinateFrameId", "urn:vao:test:missing"
            ),
            lambda m: m["acoustics"]["geometryBindings"][0].__setitem__(
                "logicalAssetId", "urn:vao:fixture:acousticrooms:asset:rir"
            ),
            lambda m: m["acoustics"]["poses"][2].__setitem__(
                "orientationUncertainty",
                {
                    "kind": "standard",
                    "value": 0.01,
                    "unit": "http://qudt.org/vocab/unit/SEC",
                },
            ),
            lambda m: m["acoustics"]["materialModels"][0].__setitem__(
                "representationStatus", "measured"
            ),
            lambda m: next(
                r
                for r in m["realizations"]
                if "impulseResponse" in r["technicalMetadata"]
            )["technicalMetadata"]["impulseResponse"]["measurementMappings"][
                0
            ].__setitem__("channelIndices", [1]),
            lambda m: next(
                r
                for r in m["realizations"]
                if "impulseResponse" in r["technicalMetadata"]
            )["technicalMetadata"]["impulseResponse"]["measurementMappings"].append(
                copy.deepcopy(
                    next(
                        r
                        for r in m["realizations"]
                        if "impulseResponse" in r["technicalMetadata"]
                    )["technicalMetadata"]["impulseResponse"]["measurementMappings"][0]
                )
            ),
            lambda m: m["acoustics"]["responseSets"][0].__setitem__(
                "interpolation",
                {
                    "method": "linear",
                    "domain": m["acoustics"]["responseSets"][0]["responseEntityId"],
                    "outsideDomainPolicy": "fallback",
                },
            ),
            lambda m: m["acoustics"]["audioScenes"][0]["bindings"][0].__setitem__(
                "mediaAssetId", "urn:vao:test:cuntz-positiv:asset:model:keyboard"
            ),
            lambda m: m["acoustics"]["renderConfigurations"][0]["listener"].__setitem__(
                "receiverId", "urn:vao:fixture:acousticrooms:source:0"
            ),
            lambda m: m["acoustics"]["renderConfigurations"][0]["listener"].__setitem__(
                "trajectoryRealizationId", m["realizations"][0]["id"]
            ),
            lambda m: m["acoustics"]["materialModels"][0].__setitem__(
                "thicknessMeters", 0
            ),
        ]
        for mutate in mutations:
            with self.subTest(mutate=mutate):
                value = json.loads(ACOUSTIC_FIXTURE.read_text(encoding="utf-8"))
                mutate(value)
                self.assertFalse(vao04.validate_manifest(value)["valid"])

        value = json.loads(ACOUSTIC_FIXTURE.read_text(encoding="utf-8"))
        asset_id = value["acoustics"]["audioScenes"][0]["bindings"][0]["mediaAssetId"]
        original = next(
            realization
            for realization in value["realizations"]
            if realization["assetId"] == asset_id
        )
        alternate = copy.deepcopy(original)
        alternate["id"] = "urn:vao:test:alternate-channel-layout"
        alternate["sha256"] = "8" * 64
        alternate["contentDigests"] = [{"algorithm": "sha256", "value": "8" * 64}]
        alternate["technicalMetadata"]["channelCount"] = 2
        value["realizations"].append(alternate)
        next(asset for asset in value["logicalAssets"] if asset["id"] == asset_id)[
            "realizationIds"
        ].append(alternate["id"])
        activity_id = alternate["provenanceIds"][0]
        next(
            activity
            for activity in value["scientific"]["activities"]
            if activity["id"] == activity_id
        )["outputIds"].append(alternate["id"])
        report = vao04.validate_manifest(value)
        self.assertFalse(report["valid"])
        self.assertIn("ambiguous channel indices", "\n".join(report["errors"]))

        value = json.loads(ACOUSTIC_FIXTURE.read_text(encoding="utf-8"))
        pose = value["acoustics"]["poses"][0]
        pose["interpolation"] = "linear"
        pose["trajectoryRealizationId"] = value["logicalAssets"][0]["id"]
        self.assertFalse(vao04.validate_manifest(value)["valid"])

        pose["trajectoryRealizationId"] = value["realizations"][0]["id"]
        report = vao04.validate_manifest(value)
        self.assertFalse(report["valid"])
        self.assertTrue(
            any("not trajectory-capable" in error for error in report["errors"]),
            report["errors"],
        )

        trajectory_technical = value["realizations"][0]["technicalMetadata"]
        trajectory_technical["kind"] = "trajectory"
        trajectory_technical["timebaseId"] = value["multimodal"]["timebases"][0]["id"]
        trajectory_technical.pop("coordinateFrameId", None)
        report = vao04.validate_manifest(value)
        self.assertFalse(report["valid"])
        self.assertTrue(
            any(
                "trajectory realization frame differs" in error
                for error in report["errors"]
            ),
            report["errors"],
        )

    def test_small_but_nonsingular_spatial_scale_is_valid(self) -> None:
        value = json.loads(ACOUSTIC_FIXTURE.read_text(encoding="utf-8"))
        value["acoustics"]["coordinateFrames"][1]["transformToParent"] = [
            1e-8,
            0,
            0,
            0,
            0,
            1e-8,
            0,
            0,
            0,
            0,
            1e-8,
            0,
            0,
            0,
            0,
            1,
        ]
        self.assertTrue(vao04.validate_manifest(value)["valid"])

        for scale in (1e-200, 1e200):
            with self.subTest(scale=scale):
                value = json.loads(ACOUSTIC_FIXTURE.read_text(encoding="utf-8"))
                value["acoustics"]["coordinateFrames"][1]["transformToParent"] = [
                    scale,
                    0,
                    0,
                    0,
                    0,
                    scale,
                    0,
                    0,
                    0,
                    0,
                    scale,
                    0,
                    0,
                    0,
                    0,
                    1,
                ]
                self.assertTrue(vao04.validate_manifest(value)["valid"])

        value = json.loads(ACOUSTIC_FIXTURE.read_text(encoding="utf-8"))
        value["acoustics"]["coordinateFrames"][1]["transformToParent"] = [
            1e-13,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            1,
        ]
        self.assertFalse(vao04.validate_manifest(value)["valid"])

    def test_geodetic_uncertainty_uses_component_axis_units(self) -> None:
        value = json.loads(ACOUSTIC_FIXTURE.read_text(encoding="utf-8"))
        frame = copy.deepcopy(value["acoustics"]["coordinateFrames"][2])
        frame["id"] = "urn:vao:test:frame:geodetic"
        frame.update(
            {
                "coordinateType": "geodetic",
                "handedness": "not-applicable",
                "upAxis": "not-applicable",
                "forwardAxis": "not-applicable",
                "axisUnits": [
                    "http://qudt.org/vocab/unit/DEG",
                    "http://qudt.org/vocab/unit/DEG",
                    "http://qudt.org/vocab/unit/M",
                ],
                "crs": "https://www.opengis.net/def/crs/OGC/1.3/CRS84h",
            }
        )
        frame.pop("unit")
        value["acoustics"]["coordinateFrames"].append(frame)
        pose = value["acoustics"]["poses"][2]
        pose["frameId"] = frame["id"]
        pose.pop("orientationXYZW")
        pose.pop("localFrameId")
        pose["positionUncertainty"] = {
            "kind": "standard",
            "value": [0.00001, 0.00001, 0.02],
            "axisUnits": frame["axisUnits"],
        }
        self.assertTrue(vao04.validate_manifest(value)["valid"])
        pose["positionUncertainty"]["axisUnits"] = pose["positionUncertainty"][
            "axisUnits"
        ][:-1]
        self.assertFalse(vao04.validate_manifest(value)["valid"])
        pose["positionUncertainty"] = {
            "kind": "registration-rms",
            "value": 0.02,
            "unit": "http://qudt.org/vocab/unit/M",
            "method": (
                "Root-mean-square residual after local metric projection of "
                "the geodetic control points."
            ),
        }
        self.assertTrue(vao04.validate_manifest(value)["valid"])
        pose["positionUncertainty"].pop("method")
        report = vao04.validate_manifest(value)
        self.assertFalse(report["valid"])
        self.assertIn("method", "\n".join(report["errors"]))

    def test_reference_interoperability_projections(self) -> None:
        value = fixture()
        value["discovery"]["relatedIdentifiers"].append(
            {
                "identifier": "https://example.org/related/object",
                "identifierType": "URL",
                "relationType": "Other",
                "relationTypeInformation": "Domain-specific contextual relation",
            }
        )
        ro_crate = vao04_interop.ro_crate(value)
        self.assertEqual(vao04_interop.RO_CRATE_CONTEXT, ro_crate["@context"])
        graph = {item["@id"]: item for item in ro_crate["@graph"]}
        metadata = graph["ro-crate-metadata.json"]
        root = graph["./"]
        self.assertEqual(
            {"@id": vao04_interop.RO_CRATE_PROFILE}, metadata["conformsTo"]
        )
        self.assertEqual(value["description"]["en"], root["description"])
        self.assertEqual(
            str(value["discovery"]["publicationYear"]), root["datePublished"]
        )
        self.assertTrue(root["license"])
        self.assertEqual(
            {activity["id"] for activity in value["scientific"]["activities"]},
            {reference["@id"] for reference in root["mentions"]},
        )
        self.assertTrue(
            all(
                "Profile" in graph[profile["id"]]["@type"]
                for profile in value["profiles"]
            )
        )
        files = [item for item in graph.values() if item.get("@type") == "File"]
        self.assertTrue(files)
        self.assertTrue(all(isinstance(item["contentSize"], str) for item in files))
        for activity in value["scientific"]["activities"]:
            for identifier in activity["inputIds"] + activity["outputIds"]:
                self.assertIn(identifier, graph)
        datacite = vao04_interop.datacite(value)["data"]["attributes"]
        self.assertEqual("Synthetic fixture performer", datacite["creators"][0]["name"])
        self.assertEqual(
            {"name": "VAO synthetic fixture project"}, datacite["publisher"]
        )
        self.assertEqual(2026, datacite["publicationYear"])
        self.assertIsInstance(datacite["rightsList"][0]["rights"], str)
        self.assertEqual(
            "Other", datacite["fundingReferences"][0]["funderIdentifierType"]
        )
        self.assertNotIn("nameType", datacite["contributors"][0])
        self.assertEqual(
            "URL", datacite["relatedIdentifiers"][-1]["relatedIdentifierType"]
        )
        self.assertEqual(
            "Domain-specific contextual relation",
            datacite["relatedIdentifiers"][-1]["relationTypeInformation"],
        )
        self.assertEqual(2, len(vao04_interop.iiif_presentation(value)["items"]))
        ocfl = vao04_interop.ocfl_inventory(value)
        self.assertEqual("v1", ocfl["head"])
        self.assertTrue(
            all(
                path.startswith("v1/content/")
                for paths in ocfl["manifest"].values()
                for path in paths
            )
        )

        without_publication_year = copy.deepcopy(value)
        without_publication_year["discovery"].pop("publicationYear")
        with self.assertRaisesRegex(ValueError, "publicationYear"):
            vao04_interop.ro_crate(without_publication_year)
        self.assertTrue(
            all(
                not path.startswith("v1/content/")
                for paths in ocfl["versions"]["v1"]["state"].values()
                for path in paths
            )
        )


if __name__ == "__main__":
    unittest.main()
